sonar.projectKey=usuario_rol_mf
sonar.projectName=usuario_rol_mf
sonar.projectVersion=1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.scss,**/coverage/**,**/dist/**
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts
sonar.typescript.tsconfigPath=tsconfig.json
sonar.javascript.lcov.reportPaths=coverage/**/lcov.info

sonar.sourceEncoding=UTF-8